/**
 * 知识库侧边栏（页面树）。
 *
 * 存在的理由（信息架构）：研究员引 NN/g 的结论——**面包屑不能替代本地导航**
 * （breadcrumbs 是"补充"，不是"主入口"），所以详情页再多面包屑也不等于"能逛"。
 * 侧边栏才是知识库的常驻地图；同时它顺手解决了另一个问题：**层级 slug 此前没有任何
 * 可视化入口**（`guide/intro` 只能靠列表里的字符串看出来是两层）。
 *
 * ## 无障碍约定（查证后按此实现）
 * - 外层 `<nav aria-label="知识库导航">`：地标 + 名字，屏幕阅读器可跳到它；
 * - 分组用 `<button aria-expanded>` 而不是可点击的 `<div>`——展开态是**状态**，
 *   必须能被读出（`div + onClick` 对键盘与读屏都是不可用的）；
 * - 子项用**嵌套 `<ul>`** 表达层级（树的语义），而不是靠缩进暗示；
 * - 当前页标 `aria-current="page"`（不是只上色）；
 * - 分组"有落地页"时，**分组名本身是链接**（点击打开该页），展开/折叠由右侧小按钮负责——
 *   一个控件只做一件事，避免"点一下既跳转又展开"这种不可预测的行为。
 *
 * ## 类目落地页语义（参考 Docusaurus autogenerated sidebar）
 * `guide` 自身也是页面时，它是该分组的落地页：分组名显示为链接、可打开；
 * 若 `guide` 不是页面（纯分组），分组名只用于展开/折叠，不可导航。
 *
 * ## 响应式
 * 桌面（`lg` 及以上）常驻在内容左侧；窄屏默认收起，由顶部按钮唤出为**抽屉**
 * （复用既有 `Dialog` 原语——它已经解决了焦点陷阱、Escape 关闭、`aria-modal`，
 * 自己写一个抽屉等于把这些重做一遍且大概率漏掉）。
 */
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import { ChevronDown, ChevronRight, FileText, PanelLeft, X } from 'lucide-react'
import {
  ancestorPaths,
  buildNavTree,
  containsSlug,
  countPages,
  navLabelOf,
  navOrderMap,
  pruneHidden,
  type NavNode,
} from '../lib/navTree'
import type { PageSummary } from '../api'
import { cn } from '../ui/cn'
import { Button } from '../ui/Button'
import { useAuth } from '../lib/authStore'
import { NewPageAction, newPageEntry } from '../lib/newPageGate'
import { Dialog, DialogContent } from '../ui/Dialog'
import { EmptyState } from '../ui/EmptyState'
import { Skeleton } from '../ui/Skeleton'

export interface SidebarProps {
  pages: PageSummary[] | null
  /** 同级顺序（与 `pages` 同一次请求下发）；缺省 = 全部按段名字典序 */
  navOrder?: readonly { parent: string; items: readonly string[] }[]
  error: string | null
  /** 当前 slug（列表/新建等非详情态传 null） */
  activeSlug: string | null
  onOpen: (slug: string) => void
  onNavigate: (path: string) => void
}

/** 详情页地址（slug 里的 `/` 必须编码，否则会被路由当成多一段 → 404） */
export function wikiHref(slug: string): string {
  return `#/wiki/${encodeURIComponent(slug)}`
}

/* ------------------------------- 单个节点 ------------------------------- */

function NodeRow(props: {
  node: NavNode
  depth: number
  activeSlug: string | null
  expanded: ReadonlySet<string>
  onToggle: (path: string) => void
  onOpen: (slug: string) => void
  /** 抽屉里点击后应关闭抽屉（桌面不需要） */
  closeOnNavigate?: boolean
}): ReactNode {
  const { node, depth, activeSlug, expanded, onToggle, onOpen } = props
  const hasChildren = node.children.length > 0
  const isOpen = expanded.has(node.path)
  const isActive = activeSlug !== null && node.page !== null && node.page.slug === activeSlug
  // 当前页在该子树内 ⇒ 祖先链上加一点暗示（但不做整行高亮，避免与"当前页"混淆）
  const inPath = activeSlug !== null && hasChildren && containsSlug(node, activeSlug)
  // 标签种类：有页面 ⇒ 页面标题；无页面（纯分组）⇒ 退回路径段并按"标识符"渲染
  const groupLabel = navLabelOf(node.segment, node.page)

  return (
    <li>
      <div
        className={cn(
          'group flex items-center gap-0.5 rounded-md',
          // 当前页高亮：底色 + 左侧竖条（不只靠颜色，符合"不要只靠颜色传达信息"）
          isActive && 'bg-accent-soft',
        )}
      >
        {isActive && <span aria-hidden="true" className="h-4 w-0.5 shrink-0 rounded-full bg-accent" />}

        {hasChildren && (
          <button
            type="button"
            onClick={() => onToggle(node.path)}
            aria-expanded={isOpen}
            aria-label={`${isOpen ? '折叠' : '展开'}「${navLabelOf(node.segment, node.page).text}」`}
            // 触控目标 ≥24×24（WCAG 2.5.8 AA）：14px 图标 + p-1.5 两侧 = 26px
            className="gw-focus-ring rounded-md p-1.5 text-muted hover:bg-hover hover:text-ink"
          >
            {isOpen ? <ChevronDown className="size-3.5" /> : <ChevronRight className="size-3.5" />}
          </button>
        )}
        {!hasChildren && <span aria-hidden="true" className="w-[26px] shrink-0" />}

        {node.page !== null ? (
          <a
            href={wikiHref(node.page.slug)}
            aria-current={isActive ? 'page' : undefined}
            onClick={() => onOpen(node.page?.slug ?? '')}
            className={cn(
              'gw-focus-ring min-w-0 flex-1 truncate rounded-md px-1.5 py-1 text-note',
              /*
                当前项底色是 `bg-accent-soft`（见上方 isActive），故前景必须用**它的配套** ink
                `text-accent-soft-ink`，而不是 `text-accent-ink`。
                `--gw-accent-ink` 是"**实心** accent 底上的字色"（白/近黑），配 `bg-accent` 才对
                （见 ui/Button.tsx 的 primary）；用在浅色柔底上会得到 **1.09:1**（深色 1.14:1）
                ——几乎不可读，axe 记为 serious。仓库里其它三处柔底（CommandPalette、
                DropdownMenu、Badge）都已经是 `text-accent-soft-ink`，只有侧栏这一处错配。
                实测对比度：浅色 #1e40af on #eff6ff = **8.01**；深色 #93c5fd on #10203a = **9.03**。
              */
              isActive ? 'font-semibold text-accent-soft-ink' : inPath ? 'text-ink' : 'text-ink-soft',
              'hover:underline',
            )}
            title={node.page.slug}
          >
            {node.page.title}
          </a>
        ) : (
          // 纯分组：名字本身不可导航（没有页面可打开），但仍需可聚焦以支持键盘展开。
          // 标签走 navLabelOf —— 无页面时只能退回 slug 段，故**明确渲染为"标识符"**
          // （等宽 + 弱化 + title 说明），而不是让它看起来像页面标题。
          <button
            type="button"
            onClick={() => onToggle(node.path)}
            aria-expanded={isOpen}
            title={`分组「${groupLabel.text}」——尚无同名页面，名称取自路径`}
            className={cn(
              'gw-focus-ring min-w-0 flex-1 truncate rounded-md px-1.5 py-1 text-left text-note font-medium text-ink-soft',
              groupLabel.kind === 'segment' && 'font-mono text-xs',
            )}
          >
            {groupLabel.text}
          </button>
        )}
      </div>

      {hasChildren && isOpen && (
        // 嵌套列表 = 树的语义（不是靠缩进暗示层级）
        <ul className="m-0 mt-0.5 flex list-none flex-col gap-0.5 pl-4">
          {node.children.map((child) => (
            <NodeRow
              key={child.path}
              node={child}
              depth={depth + 1}
              activeSlug={activeSlug}
              expanded={expanded}
              onToggle={props.onToggle}
              onOpen={props.onOpen}
            />
          ))}
        </ul>
      )}
    </li>
  )
}

/* -------------------------------- 侧栏本体 -------------------------------- */

function SidebarBody(props: SidebarProps & { closeOnNavigate?: boolean }): ReactNode {
  const { pages, error, activeSlug, onOpen, navOrder } = props
  /*
   * 树先建全（`buildNavTree` 负责把"有效隐藏"算进每个节点：父级隐藏 ⇒ 整棵子树有效隐藏），
   * 再**剪掉**隐藏的部分给侧栏用。
   *
   * 为什么不直接不把隐藏页传给 `buildNavTree`：那样"父级隐藏 ⇒ 子级也藏"就得在调用方
   * 自己实现一遍继承（第二份规则）。这里保持"继承只有一处实现"。
   */
  const order = useMemo(() => navOrderMap(navOrder), [navOrder])
  const tree = useMemo(() => pruneHidden(buildNavTree(pages ?? [], order)), [pages, order])
  // "N 个页面"与用户能在侧栏里点到的条目数一致（`countPages` 自身也跳过隐藏项）
  const total = useMemo(() => countPages(tree), [tree])
  /*
   * 空态里的「新建页面」也必须过门控（本批 G1）：侧栏此前是无条件可点的，
   * 匿名点进去会拿到完整编辑器、填完一屏、保存才 401 —— 与列表页当初那个缺陷同形。
   * 判据与列表页/路由**同一来源**（`lib/newPageGate.tsx`），不在这里自己写一套。
   * `useAuth()` 必须在任何 early return 之前调用（hook 顺序不能随分支改变，React #310）。
   */
  const auth = useAuth()
  const newEntry = newPageEntry(auth.user, auth.capabilities)

  // 展开态：默认展开当前页的祖先链；用户手动开合后以用户为准
  const [manual, setManual] = useState<ReadonlySet<string>>(new Set())
  useEffect(() => {
    if (activeSlug === null) return
    setManual((prev) => {
      const next = new Set(prev)
      for (const p of ancestorPaths(activeSlug)) {
        // 祖先链**强制展开**（含自身）：否则"当前页高亮"会藏在折叠的分组里
        if (p !== activeSlug) next.add(p)
      }
      return next
    })
  }, [activeSlug])

  const expanded = useMemo(() => {
    const s = new Set(manual)
    if (activeSlug !== null) {
      for (const p of ancestorPaths(activeSlug)) if (p !== activeSlug) s.add(p)
    }
    return s
  }, [manual, activeSlug])

  const toggle = (path: string): void => {
    setManual((prev) => {
      const next = new Set(prev)
      if (next.has(path)) next.delete(path)
      else next.add(path)
      return next
    })
  }

  if (error !== null) {
    /*
      侧栏**不重复呈现**列表加载失败，也**不泄漏原始 message**。
      理由：同一个失败已经在列表区域的 `ErrorState` 里说清并给了重试入口（重试入口只能有一个）；
      侧栏若把同一句话再印一遍，一屏上就出现两处"同一个错"，而且原文可能带 API 路径等技术细节。
      这里只表明"这一栏现在不可用"——它自己的状态，不是那个错误的副本。
    */
    return (
      <p className="m-0 px-1 text-xs text-muted" role="status">
        目录暂不可用
      </p>
    )
  }
  if (pages === null) {
    return (
      <div className="flex flex-col gap-2 px-1" aria-hidden="true">
        {[0, 1, 2, 3, 4].map((i) => (
          <Skeleton key={i} className={cn('h-5', i % 3 === 0 ? 'w-3/4' : i % 3 === 1 ? 'w-full' : 'w-2/3')} />
        ))}
      </div>
    )
  }
  if (total === 0) {
    return (
      <EmptyState
        icon={<FileText className="size-6" />}
        title="还没有页面"
        hint="创建第一个页面后，它会出现在这里。"
        action={
          <NewPageAction entry={newEntry} onNew={() => props.onNavigate('new')} size="sm" />
        }
      />
    )
  }

  return (
    <ul className="m-0 flex list-none flex-col gap-0.5 p-0">
      {tree.map((node) => (
        <NodeRow
          key={node.path}
          node={node}
          depth={0}
          activeSlug={activeSlug}
          expanded={expanded}
          onToggle={toggle}
          onOpen={(slug) => {
            onOpen(slug)
            if (props.closeOnNavigate === true) props.onNavigate(slug)
          }}
        />
      ))}
    </ul>
  )
}

/** 桌面常驻侧边栏（`lg` 及以上可见）；窄屏隐藏，由 {@link SidebarDrawer} 承担 */
export function Sidebar(props: SidebarProps & { header?: ReactNode }): ReactNode {
  return (
    <nav
      aria-label="知识库导航"
      className="hidden w-60 shrink-0 lg:block"
    >
      <div className="sticky top-[var(--spacing-gutter)] flex max-h-[calc(100vh-6rem)] flex-col gap-2 overflow-y-auto pr-1">
        {props.header}
        <SidebarBody {...props} />
      </div>
    </nav>
  )
}

/**
 * 窄屏抽屉。复用既有 `Dialog` 原语：焦点陷阱、Escape 关闭、`aria-modal`、
 * 滚动锁定都已由它（Radix）处理——这些恰是手写抽屉最容易漏的部分。
 */
export function SidebarDrawer(
  props: SidebarProps & { header?: ReactNode },
): ReactNode {
  const [open, setOpen] = useState(false)
  return (
    <>
      <Button
        size="sm"
        onClick={() => setOpen(true)}
        icon={<PanelLeft className="size-3.5" />}
        aria-haspopup="dialog"
        aria-expanded={open}
        className="lg:hidden"
      >
        目录
      </Button>
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogContent title="知识库目录" description="按路径分组，点击分组可展开/折叠">
          <div className="flex max-h-[70vh] flex-col gap-2 overflow-y-auto">
            {props.header}
            <SidebarBody {...props} closeOnNavigate />
          </div>
        </DialogContent>
      </Dialog>
    </>
  )
}

/**
 * 窄屏"关闭抽屉"按钮（若 Dialog 未内置关闭按钮则由调用方渲染）。
 * 目前 Dialog 头里已有 X —— 保留此导出仅为将来可替换。
 */
export function DrawerCloseButton(props: { onClick: () => void }): ReactNode {
  return (
    <button
      type="button"
      onClick={props.onClick}
      aria-label="关闭目录"
      className="gw-focus-ring rounded-md p-1 text-muted hover:bg-hover"
    >
      <X className="size-4" />
    </button>
  )
}
