/**
 * `slug 列表 → 导航树`（纯函数，可 `node:test` 单测）。
 *
 * 为什么单独一层：树的形状决定侧边栏的全部行为（分组、展开、类目落地页、当前页祖先链），
 * 而它本质上是"字符串数组 → 结构"的确定性变换。把它从组件里抽出来，边界
 * （乱序输入、只有 `a/b/c` 没有 `a`、`guide` 本身是页面、同名前缀冲突）都能用单测钉住，
 * 而不必启动浏览器。
 *
 * 层级约定参考 Docusaurus 的 autogenerated sidebar：**目录 = 分组**，而
 * "`guide` 自身也是一个页面"时它同时充当**类目落地页**（点击分组先打开这一页）。
 */

/** 树的叶子/节点共用的一种表示：一个页面（可能是分组自身的落地页） */
export interface NavPage {
  slug: string
  title: string
  updated_at: string
  version: number
}

export interface NavNode {
  /** 该节点对应的**路径段名**（分组名，或叶子 slug 的末段） */
  segment: string
  /** 该节点的完整 slug 前缀（用于拼链接与判"当前页是否在此子树下"） */
  path: string
  /** 该节点**自身**是否有页面（有 ⇒ 点击分组可打开它，即"类目落地页"） */
  page: NavPage | null
  /** 子节点（按 `segment` 字典序） */
  children: NavNode[]
}

/**
 * 排序键：**字典序**，不是 `updated_at`。
 *
 * 为什么不用 `updated_at`（与列表页的默认排序不同）：侧边栏是"地图"，位置必须稳定——
 * 若按更新时间排，用户每编辑一页侧边栏就重排，肌肉记忆失效，且同一页在两处的邻居不同。
 * 用 `Intl.Collator` 且显式区分大小写敏感度，保证跨环境结果一致（`localeCompare` 的
 * 默认行为随 ICU 版本变化，会让"测试在我机器上是绿的"）。
 */
const collator = new Intl.Collator('en', { sensitivity: 'variant', numeric: true })

export function compareSegment(a: string, b: string): number {
  return collator.compare(a, b)
}

/**
 * 把页面列表聚合成树。
 *
 * 行为要点：
 * - 输入**可以是乱序的**（后端按更新时间排，树的顺序由本函数重新决定）；
 * - 中间层**不需要存在页面**：只有 `a/b/c` 时会生成 `a` → `b` → `c` 三层，
 *   其中 `a`、`b` 的 `page` 为 `null`（表示"纯分组"）；
 * - `guide` 自身是页面时，它既是分组又是可打开的页面（`page !== null`）；
 * - 同名 slug 重复出现时**保留第一个**并跳过后续（后端 slug 唯一，这里是防御性去重）。
 */
export function buildNavTree(pages: readonly NavPage[]): NavNode[] {
  const roots: NavNode[] = []
  /** path → 节点，便于 O(深度) 找到中间层 */
  const byPath = new Map<string, NavNode>()

  const ensure = (path: string, segment: string, parent: NavNode[]): NavNode => {
    const found = byPath.get(path)
    if (found !== undefined) return found
    const node: NavNode = { segment, path, page: null, children: [] }
    byPath.set(path, node)
    parent.push(node)
    return node
  }

  for (const p of pages) {
    const segs = p.slug.split('/').filter((s) => s !== '')
    if (segs.length === 0) continue // 防御：空 slug 不该出现（后端 isValidSlug 已拒）
    let level = roots
    let path = ''
    for (let i = 0; i < segs.length; i += 1) {
      const seg = segs[i] as string
      path = path === '' ? seg : `${path}/${seg}`
      const node = ensure(path, seg, level)
      if (i === segs.length - 1) {
        if (node.page === null) node.page = p // 只认第一个（防御性去重）
      }
      level = node.children
    }
  }

  sortRecursive(roots)
  return roots
}

function sortRecursive(nodes: NavNode[]): void {
  nodes.sort((a, b) => compareSegment(a.segment, b.segment))
  for (const n of nodes) sortRecursive(n.children)
}

/**
 * 当前页所在的**祖先路径集合**（含自身），用于"父分组自动展开"。
 *
 * 例：当前 `guide/setup/install` → `['guide', 'guide/setup', 'guide/setup/install']`。
 * 前缀累积的顺序即从根到叶，调用方可直接逐个 `expanded.add(...)`。
 */
export function ancestorPaths(slug: string): string[] {
  const segs = slug.split('/').filter((s) => s !== '')
  const out: string[] = []
  let path = ''
  for (const seg of segs) {
    path = path === '' ? seg : `${path}/${seg}`
    out.push(path)
  }
  return out
}

/** 节点自身或其后代**是否包含**给定 slug（用于高亮当前页的祖先链） */
export function containsSlug(node: NavNode, slug: string): boolean {
  if (node.path === slug) return true
  // slug 以 `path + '/'` 开头即属于该子树——比遍历整棵子树便宜
  return slug.startsWith(`${node.path}/`)
}

/**
 * 按**展示顺序**展平树，得到"可阅读的页面序列"。
 *
 * 顺序定义与 {@link Sidebar} 的渲染顺序**逐字对应**：先节点自身的页面（若有），再递归其子节点。
 * 这条对应关系是本函数的全部意义——"上一篇/下一篇"必须与用户在侧边栏看到的上下关系一致，
 * 否则会出现"下一篇"从「指南」组跳到「运维手册」组这种断裂（先用 `updated_at DESC` 时的实际症状）。
 *
 * 中间层若没有页面（纯分组，如只有 `a/b/c` 而没有 `a`）**不入序列**：它不可打开，
 * 不该在翻页里占一步（否则用户点"下一篇"会落到一个打不开的分组名上）。
 *
 * 输入假定已由 {@link buildNavTree} 排好序（本函数不重新排序，以免与侧边栏出现两套顺序）。
 */
export function flattenPages(nodes: readonly NavNode[]): NavPage[] {
  const out: NavPage[] = []
  const walk = (list: readonly NavNode[]): void => {
    for (const node of list) {
      if (node.page !== null) out.push(node.page)
      walk(node.children)
    }
  }
  walk(nodes)
  return out
}

/**
 * 取某页在**展示顺序**里的相邻页（第一项无上一篇、最后一项无下一篇）。
 *
 * 同 slug 出现多次时以第一次为准（`buildNavTree` 已做防御性去重，这里保持一致）。
 * 找不到该 slug 时返回 `index: -1` 且两个邻居都为 `undefined`——调用方据此不渲染翻页条。
 */
export function neighborsOf(
  nodes: readonly NavNode[],
  slug: string,
): { prev: NavPage | undefined; next: NavPage | undefined; index: number } {
  const flat = flattenPages(nodes)
  const index = flat.findIndex((p) => p.slug === slug)
  if (index < 0) return { prev: undefined, next: undefined, index: -1 }
  return {
    prev: index > 0 ? flat[index - 1] : undefined,
    next: index < flat.length - 1 ? flat[index + 1] : undefined,
    index,
  }
}

/**
 * 树的规模统计（供"全部展开/折叠"与空态判断用）。
 * 返回的是**可导航条目**数量（分组本身若没有页面则不计），用于侧边栏标题的"N 个页面"。
 */
export function countPages(nodes: readonly NavNode[]): number {
  let n = 0
  for (const node of nodes) {
    if (node.page !== null) n += 1
    n += countPages(node.children)
  }
  return n
}
