/**
 * `slug 列表 → 导航树`（纯函数，可 `node:test` 单测）。
 *
 * 为什么单独一层：树的形状决定侧边栏的全部行为（分组、展开、类目落地页、当前页祖先链），
 * 而它本质上是"字符串数组 → 结构"的确定性变换。把它从组件里抽出来，边界
 * （乱序输入、只有 `a/b/c` 没有 `a`、`guide` 本身是页面、同名前缀冲突）都能用单测钉住，
 * 而不必启动浏览器。
 *
 * 层级约定参考 Docusaurus 的 autogenerated sidebar：**目录 = 分组**，而
 * "`guide` 自身也是一个页面"时它同时充当**类目落地页**（点击分组先打开这一页）。
 */

/** 树的叶子/节点共用的一种表示：一个页面（可能是分组自身的落地页） */
export interface NavPage {
  slug: string
  title: string
  updated_at: string
  version: number
}

export interface NavNode {
  /** 该节点对应的**路径段名**（分组名，或叶子 slug 的末段） */
  segment: string
  /** 该节点的完整 slug 前缀（用于拼链接与判"当前页是否在此子树下"） */
  path: string
  /** 该节点**自身**是否有页面（有 ⇒ 点击分组可打开它，即"类目落地页"） */
  page: NavPage | null
  /** 子节点（按 `segment` 字典序） */
  children: NavNode[]
}

/**
 * 排序键：**字典序**，不是 `updated_at`。
 *
 * 为什么不用 `updated_at`（与列表页的默认排序不同）：侧边栏是"地图"，位置必须稳定——
 * 若按更新时间排，用户每编辑一页侧边栏就重排，肌肉记忆失效，且同一页在两处的邻居不同。
 * 用 `Intl.Collator` 且显式区分大小写敏感度，保证跨环境结果一致（`localeCompare` 的
 * 默认行为随 ICU 版本变化，会让"测试在我机器上是绿的"）。
 */
const collator = new Intl.Collator('en', { sensitivity: 'variant', numeric: true })

export function compareSegment(a: string, b: string): number {
  return collator.compare(a, b)
}

/**
 * 把页面列表聚合成树。
 *
 * 行为要点：
 * - 输入**可以是乱序的**（后端按更新时间排，树的顺序由本函数重新决定）；
 * - 中间层**不需要存在页面**：只有 `a/b/c` 时会生成 `a` → `b` → `c` 三层，
 *   其中 `a`、`b` 的 `page` 为 `null`（表示"纯分组"）；
 * - `guide` 自身是页面时，它既是分组又是可打开的页面（`page !== null`）；
 * - 同名 slug 重复出现时**保留第一个**并跳过后续（后端 slug 唯一，这里是防御性去重）。
 */
export function buildNavTree(pages: readonly NavPage[]): NavNode[] {
  const roots: NavNode[] = []
  /** path → 节点，便于 O(深度) 找到中间层 */
  const byPath = new Map<string, NavNode>()

  const ensure = (path: string, segment: string, parent: NavNode[]): NavNode => {
    const found = byPath.get(path)
    if (found !== undefined) return found
    const node: NavNode = { segment, path, page: null, children: [] }
    byPath.set(path, node)
    parent.push(node)
    return node
  }

  for (const p of pages) {
    const segs = p.slug.split('/').filter((s) => s !== '')
    if (segs.length === 0) continue // 防御：空 slug 不该出现（后端 isValidSlug 已拒）
    let level = roots
    let path = ''
    for (let i = 0; i < segs.length; i += 1) {
      const seg = segs[i] as string
      path = path === '' ? seg : `${path}/${seg}`
      const node = ensure(path, seg, level)
      if (i === segs.length - 1) {
        if (node.page === null) node.page = p // 只认第一个（防御性去重）
      }
      level = node.children
    }
  }

  sortRecursive(roots)
  return roots
}

function sortRecursive(nodes: NavNode[]): void {
  nodes.sort((a, b) => compareSegment(a.segment, b.segment))
  for (const n of nodes) sortRecursive(n.children)
}

/**
 * 当前页所在的**祖先路径集合**（含自身），用于"父分组自动展开"。
 *
 * 例：当前 `guide/setup/install` → `['guide', 'guide/setup', 'guide/setup/install']`。
 * 前缀累积的顺序即从根到叶，调用方可直接逐个 `expanded.add(...)`。
 */
export function ancestorPaths(slug: string): string[] {
  const segs = slug.split('/').filter((s) => s !== '')
  const out: string[] = []
  let path = ''
  for (const seg of segs) {
    path = path === '' ? seg : `${path}/${seg}`
    out.push(path)
  }
  return out
}

/** 节点自身或其后代**是否包含**给定 slug（用于高亮当前页的祖先链） */
export function containsSlug(node: NavNode, slug: string): boolean {
  if (node.path === slug) return true
  // slug 以 `path + '/'` 开头即属于该子树——比遍历整棵子树便宜
  return slug.startsWith(`${node.path}/`)
}

/**
 * 按**展示顺序**展平树，得到"可阅读的页面序列"。
 *
 * 顺序定义与 {@link Sidebar} 的渲染顺序**逐字对应**：先节点自身的页面（若有），再递归其子节点。
 * 这条对应关系是本函数的全部意义——"上一篇/下一篇"必须与用户在侧边栏看到的上下关系一致，
 * 否则会出现"下一篇"从「指南」组跳到「运维手册」组这种断裂（先用 `updated_at DESC` 时的实际症状）。
 *
 * 中间层若没有页面（纯分组，如只有 `a/b/c` 而没有 `a`）**不入序列**：它不可打开，
 * 不该在翻页里占一步（否则用户点"下一篇"会落到一个打不开的分组名上）。
 *
 * 输入假定已由 {@link buildNavTree} 排好序（本函数不重新排序，以免与侧边栏出现两套顺序）。
 */
export function flattenPages(nodes: readonly NavNode[]): NavPage[] {
  const out: NavPage[] = []
  const walk = (list: readonly NavNode[]): void => {
    for (const node of list) {
      if (node.page !== null) out.push(node.page)
      walk(node.children)
    }
  }
  walk(nodes)
  return out
}

/**
 * 取某页在**展示顺序**里的相邻页（第一项无上一篇、最后一项无下一篇）。
 *
 * 同 slug 出现多次时以第一次为准（`buildNavTree` 已做防御性去重，这里保持一致）。
 * 找不到该 slug 时返回 `index: -1` 且两个邻居都为 `undefined`——调用方据此不渲染翻页条。
 */
export function neighborsOf(
  nodes: readonly NavNode[],
  slug: string,
): { prev: NavPage | undefined; next: NavPage | undefined; index: number } {
  const flat = flattenPages(nodes)
  const index = flat.findIndex((p) => p.slug === slug)
  if (index < 0) return { prev: undefined, next: undefined, index: -1 }
  return {
    prev: index > 0 ? flat[index - 1] : undefined,
    next: index < flat.length - 1 ? flat[index + 1] : undefined,
    index,
  }
}

/**
 * 树的规模统计（供"全部展开/折叠"与空态判断用）。
 * 返回的是**可导航条目**数量（分组本身若没有页面则不计），用于侧边栏标题的"N 个页面"。
 */
export function countPages(nodes: readonly NavNode[]): number {
  let n = 0
  for (const node of nodes) {
    if (node.page !== null) n += 1
    n += countPages(node.children)
  }
  return n
}

/* ------------------------------ 面包屑 ------------------------------ */

/**
 * 面包屑的一项。**列表顺序即层级顺序**（根在首、当前页在末）。
 *
 * 为什么把「当前页」也放进这个数组（而不是像过去那样让组件自己补一个「知识库」根项）：
 * 过去分隔符有**两个来源**——根项 `<li>` 尾部硬编码一个 `ChevronRight`，而每个非末项
 * 又在**自己开头**再画一个——于是渲染成 `知识库 › › 指南 撰写指南`：
 * 第一个间隙出现**两个**分隔符，而末项之前**一个都没有**（因为末项不画）。
 * 根因不是"少写了一个分隔符"，而是**同一件事有两处负责**。
 * 现在改成：面包屑的全部项由本函数产出，分隔符只有**一条规则**（见 `hasSeparatorBefore`）。
 */
export interface BreadcrumbItem {
  /** 显示文本：有对应页面时用页面标题，纯分组退回该段路径片段，末项用传入的 `title` */
  label: string
  /** 可点击目标；`null` = 不可点（纯分组，或当前页自身） */
  href: string | null
  /** 是否为当前页（恒为数组最后一项） */
  isLast: boolean
  /** 该项对应的 slug 前缀；根项为 `''` */
  path: string
  /** 该项是否有对应的页面（false = 纯分组，用于 `title` 说明与测试断言） */
  hasPage: boolean
}

/** 面包屑根项（知识库列表）的文案与地址 */
export const BREADCRUMB_ROOT_LABEL = '知识库'
export const BREADCRUMB_ROOT_HREF = '#/wiki/list'

/**
 * 构造面包屑（纯函数）。
 *
 * `hrefOf` 由调用方注入（详情页传 `wikiHref`）而不是在本模块 import 组件模块——
 * 避免 `lib → components` 的反向依赖，同时让单测不必碰浏览器（传一个朴素实现即可）。
 *
 * 三种输入的输出：
 * - 顶层页面（`standalone`）⇒ `[知识库, 当前页]`；
 * - 中间层是页面（`guides` 存在）⇒ 中间项 `href != null`（可点）；
 * - 中间层是纯分组（只有 `guides/authoring`）⇒ 中间项 `href === null` 且 `hasPage === false`。
 *   **刻意不链到列表页**：那会给出"看起来能到、实际到别处"的假链接。
 * - 新建页（`slug` 为空）没有层级可拆 ⇒ `[知识库, {label: title}]`（否则末项会整个消失）。
 */
export function buildBreadcrumb(
  slug: string,
  title: string,
  pagesBySlug: ReadonlyMap<string, { title: string }>,
  hrefOf: (slug: string) => string,
): BreadcrumbItem[] {
  const root: BreadcrumbItem = {
    label: BREADCRUMB_ROOT_LABEL,
    href: BREADCRUMB_ROOT_HREF,
    isLast: false,
    path: '',
    hasPage: true,
  }
  const paths = ancestorPaths(slug)
  if (paths.length === 0) {
    return [root, { label: title, href: null, isLast: true, path: '', hasPage: false }]
  }
  const rest = paths.map((path, i) => {
    const page = pagesBySlug.get(path)
    const isLast = i === paths.length - 1
    const seg = path.split('/').pop() ?? path
    return {
      path,
      // 末项用传入的 title（详情已加载的最新标题），其余用清单里的标题
      label: isLast ? title : (page?.title ?? seg),
      // 当前页不可点；纯分组不可点
      href: isLast || page === undefined ? null : hrefOf(path),
      isLast,
      hasPage: page !== undefined,
    }
  })
  return [root, ...rest]
}

/**
 * 分隔符的**唯一规则**：除首项外，每项**之前**恰好一个分隔符。
 *
 * N 项 ⇒ N-1 个分隔符，且与标签**严格交替**（`label (› label)*`）。
 * 渲染与测试都走这一个函数，所以"多一个 `›`"不可能再出现——它需要第二处代码去画第二个。
 */
export function hasSeparatorBefore(index: number): boolean {
  return index > 0
}

/**
 * 把面包屑摊平成"用户看到的那一行"的 token 序列（供单测直接断言交替性）。
 *
 * 用 `SEP` 占位而不是 `›` 字面量：真实分隔符是 lucide 图标（DOM 里没有文本），
 * 这里只需要表达"**一个**分隔符位置"，避免把图标选择与断言耦合。
 */
export const BREADCRUMB_SEP = '›'

export function breadcrumbTokens(items: readonly BreadcrumbItem[]): string[] {
  const out: string[] = []
  items.forEach((item, i) => {
    if (hasSeparatorBefore(i)) out.push(BREADCRUMB_SEP)
    out.push(item.label)
  })
  return out
}

/** 中间层（既非根、也非当前页）的数量——窄屏省略提示要用 */
export function intermediateCrumbCount(items: readonly BreadcrumbItem[]): number {
  return Math.max(0, items.length - 2)
}
