-- 0001_init.sql —— 初始表结构（PostgreSQL 方言）
--
-- 与 packages/db-sqlite/src/migrations/0001_init.sql **语义等价**：
-- 同样的两张表、同样的列语义、同样的级联删除与索引。方言差异对照：
--
-- | 语义            | SQLite                       | PostgreSQL                          |
-- | --------------- | ---------------------------- | ----------------------------------- |
-- | 自增主键        | INTEGER PRIMARY KEY AUTOINCREMENT | INTEGER GENERATED BY DEFAULT AS IDENTITY |
-- | 文本            | TEXT                         | TEXT（PG 的 TEXT 无长度限制，语义一致） |
-- | 时间（ISO8601） | TEXT                         | TEXT（**刻意保持 TEXT**：应用层写入的是 |
-- |                 |                              |   new Date().toISOString()，改成        |
-- |                 |                              |   timestamptz 会让两个适配器的返回值形状 |
-- |                 |                              |   不一致，破坏"切换数据库对上层透明"）    |
-- | 外键级联        | REFERENCES … ON DELETE CASCADE | 同左（语法一致）                     |
-- | 幂等建表        | CREATE TABLE IF NOT EXISTS   | 同左                                 |
-- | 索引            | CREATE INDEX IF NOT EXISTS   | 同左                                 |
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里（与 sqlite 版一致）。

CREATE TABLE IF NOT EXISTS pages (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug        TEXT    NOT NULL UNIQUE,             -- 页面路径标识，如 "getting-started" 或 "guides/intro"
  title       TEXT    NOT NULL,                    -- 页面标题
  content     TEXT    NOT NULL DEFAULT '',         -- 页面正文（Markdown）
  created_at  TEXT    NOT NULL,                    -- ISO8601 创建时间
  updated_at  TEXT    NOT NULL                     -- ISO8601 最后更新时间
);

-- 版本历史：每次更新正文插入一条快照
CREATE TABLE IF NOT EXISTS page_versions (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id    INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  content    TEXT    NOT NULL,
  saved_at   TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_page_versions_page_id ON page_versions(page_id);

-- 列表默认按 updated_at DESC 排序并带 id DESC 次级键（分页正确性的前提），
-- 与 sqlite 侧 0002 迁移加的索引对应。
CREATE INDEX IF NOT EXISTS idx_pages_updated_at ON pages(updated_at DESC, id DESC);
