-- 0010_identity.sql —— 身份：用户、凭据、会话、外部身份（PostgreSQL 方言）
--
-- 与 packages/db-sqlite/src/migrations/0010_identity.sql **语义等价**：
-- 同样的四张表、同样的列语义、同样的级联删除与索引。方言差异对照：
--
-- | 语义            | SQLite                           | PostgreSQL                               |
-- | --------------- | -------------------------------- | ---------------------------------------- |
-- | 自增主键        | INTEGER PRIMARY KEY AUTOINCREMENT | INTEGER GENERATED BY DEFAULT AS IDENTITY |
-- | 布尔语义列      | INTEGER 0/1                      | **同样 INTEGER 0/1**（刻意不用 BOOLEAN）  |
-- | 时间（ISO8601） | TEXT                             | TEXT（**刻意保持 TEXT**：应用层写入的是   |
-- |                 |                                  |   new Date().toISOString()，改成          |
-- |                 |                                  |   timestamptz 会让两个适配器返回形状不一致）|
-- | 外键级联        | REFERENCES … ON DELETE CASCADE    | 同左                                      |
-- | 幂等建表/索引   | IF NOT EXISTS                    | 同左                                      |
--
-- **email_verified 为什么不用 BOOLEAN**：用 BOOLEAN 会让 pg 驱动回 `true/false`、
-- sqlite 回 `0/1`，业务代码必须写方言分支；两侧同为 INTEGER 时
-- `WHERE email_verified = 1` 在两种方言下语义一致（与 core 的 `asAsync`
-- "写一次代码、两种驱动都能跑"是同一取向）。
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS users (
  id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id         INTEGER NOT NULL DEFAULT 1,
  email          TEXT    NOT NULL,
  display_name   TEXT    NOT NULL,
  status         TEXT    NOT NULL DEFAULT 'active',
  email_verified INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT    NOT NULL,
  last_seen_at   TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_org_email ON users(org_id, email);

CREATE TABLE IF NOT EXISTS user_credentials (
  user_id    INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  algo       TEXT    NOT NULL,
  params     TEXT    NOT NULL,
  salt       TEXT    NOT NULL,
  hash       TEXT    NOT NULL,
  updated_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id              TEXT    PRIMARY KEY,
  user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash      TEXT    NOT NULL,
  created_at      TEXT    NOT NULL,
  last_used_at    TEXT    NOT NULL,
  expires_at      TEXT    NOT NULL,
  idle_expires_at TEXT    NOT NULL,
  revoked_at      TEXT,
  user_agent      TEXT,
  ip_hash         TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash);

CREATE TABLE IF NOT EXISTS user_identities (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  issuer        TEXT    NOT NULL,
  subject       TEXT    NOT NULL,
  email_at_link TEXT,
  linked_at     TEXT    NOT NULL,
  last_login_at TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_identities_issuer_sub ON user_identities(issuer, subject);
CREATE INDEX IF NOT EXISTS idx_identities_user ON user_identities(user_id);
