-- 0011_org_team.sql —— 组织、成员、组、邀请（PostgreSQL 方言）
--
-- 与 packages/db-sqlite/src/migrations/0011_org_team.sql **语义等价**：
-- 同样的五张表、同样的列语义、同样的级联删除、同样的索引，以及同样的默认组织种子。
-- 方言差异对照：
--
-- | 语义            | SQLite                           | PostgreSQL                               |
-- | --------------- | -------------------------------- | ---------------------------------------- |
-- | 自增主键        | INTEGER PRIMARY KEY AUTOINCREMENT | INTEGER GENERATED BY DEFAULT AS IDENTITY |
-- | 时间（ISO8601） | TEXT + strftime('%Y-…%fZ')        | TEXT + to_char(now() AT TIME ZONE 'utc') |
-- | 幂等种子        | INSERT … SELECT … WHERE NOT EXISTS | 同左                                     |
-- | 外键级联        | REFERENCES … ON DELETE CASCADE    | 同左                                      |
-- | 幂等建表/索引   | IF NOT EXISTS                    | 同左                                      |
--
-- **时间列一律 TEXT**（与 0001/0010 一致）：应用层写入的是 `new Date().toISOString()`，
-- 改成 `timestamptz` 会让两个适配器返回形状不一致，进而逼业务代码写方言分支。
--
-- **种子用 `INSERT … SELECT … WHERE NOT EXISTS` 而不是 PG 的 `ON CONFLICT DO NOTHING`**：
-- 后者在 SQLite 侧是另一套写法，会让两个文件形状分叉；统一用标准 SQL 的
-- `SELECT … WHERE NOT EXISTS` 时两侧**逐字相同**，评审时可以直接对照。
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS orgs (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug       TEXT    NOT NULL UNIQUE,
  name       TEXT    NOT NULL,
  -- 站点级默认可见性（private|public）。**P2 不消费它**：真正决定条目可见性的是
  -- pages.visibility（0012）。保留此列是为了让"站点级默认"将来有落点。
  visibility TEXT    NOT NULL DEFAULT 'private',
  created_at TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS org_members (
  org_id    INTEGER NOT NULL REFERENCES orgs(id)  ON DELETE CASCADE,
  user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- owner|admin|member|viewer。**这一列只承载能力**，不参与"谁能看哪条内容"的判定。
  role      TEXT    NOT NULL,
  joined_at TEXT    NOT NULL,
  PRIMARY KEY (org_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_org_members_user ON org_members(user_id);

CREATE TABLE IF NOT EXISTS groups (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id     INTEGER NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  name       TEXT    NOT NULL,
  created_at TEXT    NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_groups_org_name ON groups(org_id, name);

CREATE TABLE IF NOT EXISTS group_members (
  group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  user_id  INTEGER NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
  added_at TEXT    NOT NULL,
  PRIMARY KEY (group_id, user_id)
);
CREATE INDEX IF NOT EXISTS idx_group_members_user ON group_members(user_id);

CREATE TABLE IF NOT EXISTS invitations (
  id          TEXT    PRIMARY KEY,
  org_id      INTEGER NOT NULL REFERENCES orgs(id) ON DELETE CASCADE,
  email       TEXT    NOT NULL,
  -- NULL = guest 通道（入伙但不给组织角色）；
  -- ★ 这是"入伙后拿到哪个角色（能力）"，**不是授权对象**。
  org_role    TEXT,
  group_id    INTEGER REFERENCES groups(id) ON DELETE SET NULL,
  invited_by  INTEGER REFERENCES users(id)  ON DELETE SET NULL,
  token_hash  TEXT    NOT NULL,
  expires_at  TEXT    NOT NULL,
  accepted_at TEXT,
  created_at  TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_invitations_email ON invitations(org_id, email);
CREATE INDEX IF NOT EXISTS idx_invitations_expires ON invitations(expires_at);

-- ★ 默认组织种子（幂等）。与 SQLite 侧逐字相同的写法，只有取"当前时间"的表达式不同。
INSERT INTO orgs (id, slug, name, visibility, created_at)
SELECT 1,
       'default',
       '默认组织',
       'private',
       to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
WHERE NOT EXISTS (SELECT 1 FROM orgs WHERE id = 1);
