-- 0012_page_acl.sql —— 条目可见性字段 + 页面级例外授予（PostgreSQL 方言）
--
-- 与 packages/db-sqlite/src/migrations/0012_page_acl.sql **语义等价**。
-- 方言差异对照：
--
-- | 语义          | SQLite                              | PostgreSQL                |
-- | ------------- | ----------------------------------- | ------------------------- |
-- | 增列          | ALTER TABLE … ADD COLUMN（逐条）      | 同左（同样逐条，形状一致）  |
-- | 自增主键      | INTEGER PRIMARY KEY AUTOINCREMENT    | INTEGER GENERATED BY DEFAULT AS IDENTITY |
-- | 时间列        | TEXT                                | TEXT（**刻意保持 TEXT**）   |
-- | 幂等建表/索引 | IF NOT EXISTS                       | 同左                       |
--
-- **`ALTER TABLE … ADD COLUMN … NOT NULL DEFAULT` 在 PG 上会锁表并重写**：本项目的
-- pages 表规模不大（自建 wiki），因此可接受；若将来数据量上来了，这里应改成
-- "先加可空列 → 分批回填 → 再加 NOT NULL 约束"。写在这里是为了让下一位维护者
-- 在表变大时知道该动哪里，而不是等迁移超时才发现。
--
-- 其余口径（可见性三字段、两层默认值、D8 回填、D13 授权对象只有 user|group、
-- acl_revision 用代际失效而非 TTL）与 SQLite 侧逐字对应，此处不再重复解释。
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

ALTER TABLE pages ADD COLUMN visibility   TEXT    NOT NULL DEFAULT 'private';
ALTER TABLE pages ADD COLUMN inherit      INTEGER NOT NULL DEFAULT 1;
ALTER TABLE pages ADD COLUMN published_at TEXT;
ALTER TABLE pages ADD COLUMN created_by   INTEGER;
ALTER TABLE pages ADD COLUMN acl_revision INTEGER NOT NULL DEFAULT 0;
ALTER TABLE pages ADD COLUMN content_hash TEXT;

CREATE INDEX IF NOT EXISTS idx_pages_visibility ON pages(visibility, published_at);

CREATE TABLE IF NOT EXISTS page_grants (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_slug    TEXT    NOT NULL,
  -- ★ D13：只有 user|group，没有 org_role（角色只决定能力，不是授权对象）。
  subject_kind TEXT    NOT NULL,
  subject_id   TEXT    NOT NULL,
  role         TEXT    NOT NULL,   -- editor|viewer
  granted_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  granted_at   TEXT    NOT NULL,
  expires_at   TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_page_grants_unique
  ON page_grants(page_slug, subject_kind, subject_id);
CREATE INDEX IF NOT EXISTS idx_page_grants_subject
  ON page_grants(subject_kind, subject_id);

-- ★ D8：存量条目一次性回填为 `org`。与 SQLite 侧逐字相同的语句。
-- 不回填的后果：新增列默认 'private' ⇒ 升级当天全站条目对所有人不可见。
-- 'public' 绝不会被批量设置 —— 公开必须由管理员逐条显式发布（published_at）。
UPDATE pages SET visibility = 'org' WHERE visibility = 'private';
