-- 0013_audit.sql —— 全局 ACL 版本号 + 审计日志（PostgreSQL 方言）
--
-- 与 packages/db-sqlite/src/migrations/0013_audit.sql **语义等价**。方言差异仅两处：
--   1. 自增主键：INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   2. 预置单行的幂等写法：ON CONFLICT (id) DO NOTHING（sqlite 侧是 INSERT OR IGNORE）
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS acl_revision (
  id       INTEGER PRIMARY KEY CHECK (id = 1),
  revision INTEGER NOT NULL DEFAULT 1
);

INSERT INTO acl_revision (id, revision) VALUES (1, 1) ON CONFLICT (id) DO NOTHING;

-- append-only；before_json/after_json **不含**正文与凭据值（CWE-779）。
CREATE TABLE IF NOT EXISTS audit_log (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  at            TEXT    NOT NULL,
  actor_id      INTEGER,
  actor_ip_hash TEXT,
  action        TEXT    NOT NULL,
  target_kind   TEXT    NOT NULL,
  target_id     TEXT    NOT NULL,
  before_json   TEXT,
  after_json    TEXT,
  request_id    TEXT
);

CREATE INDEX IF NOT EXISTS idx_audit_at ON audit_log(at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_audit_target ON audit_log(target_kind, target_id);
CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_log(action, at DESC);
