-- 0014_access_requests.sql —— 申请访问（PostgreSQL 方言，P3b）
--
-- 与 packages/db-sqlite/src/migrations/0014_access_requests.sql **语义等价**。
-- 方言差异对照：
--
-- | 语义          | SQLite                            | PostgreSQL                                |
-- | ------------- | --------------------------------- | ----------------------------------------- |
-- | 自增主键      | INTEGER PRIMARY KEY AUTOINCREMENT | INTEGER GENERATED BY DEFAULT AS IDENTITY  |
-- | 时间列        | TEXT                              | TEXT（**刻意保持 TEXT**）                   |
-- | 幂等建表/索引 | IF NOT EXISTS                     | 同左                                      |
--
-- 其余口径（绑 slug 而非 page_id 的理由、"请求"与"授予"分开存、
-- 唯一键含 `status` 以便"拒绝后可再次申请但不允许同状态重复"）与 SQLite 侧逐字对应。
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS access_requests (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_slug    TEXT    NOT NULL,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message      TEXT,
  status       TEXT    NOT NULL DEFAULT 'pending',
  decided_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  decided_at   TEXT,
  created_at   TEXT    NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_access_req_pending
  ON access_requests(page_slug, user_id, status);

CREATE INDEX IF NOT EXISTS idx_access_req_status
  ON access_requests(status, created_at DESC);
