-- 0015_blocks.sql —— 内容块（PostgreSQL 方言，P3a）
--
-- 与 packages/db-sqlite/src/migrations/0015_blocks.sql **语义等价**。
-- 该文件头部有完整的**理由说明**（为什么 tier 内联且不给默认值、为什么落在 db 包而不是
-- `@geewiki/wiki` 的迁移目录、块身份与页面源快照的关系）—— 那些理由与方言无关，此处不重复。
--
-- 方言差异对照（与 0001_init.sql 的对照表同源）：
--
-- | 语义       | SQLite                             | PostgreSQL                                |
-- | ---------- | ---------------------------------- | ----------------------------------------- |
-- | 自增主键   | INTEGER PRIMARY KEY AUTOINCREMENT  | INTEGER GENERATED BY DEFAULT AS IDENTITY  |
-- | 文本       | TEXT                               | TEXT（PG 的 TEXT 无长度限制，语义一致）    |
-- | 时间       | TEXT（ISO8601 字符串）             | TEXT（**刻意保持 TEXT**：应用层写的是      |
-- |            |                                    |   new Date().toISOString()，改成           |
-- |            |                                    |   timestamptz 会让两个适配器的返回值形状   |
-- |            |                                    |   不一致，破坏"切换数据库对上层透明"）      |
-- | 外键级联   | REFERENCES … ON DELETE CASCADE     | 同左（语法一致）                          |
-- | 部分索引   | CREATE INDEX … WHERE …             | 同左（PG 同样支持 partial index）          |
-- | 幂等建表   | CREATE TABLE IF NOT EXISTS         | 同左                                      |
--
-- **不写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS blocks (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id       INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  ordinal       INTEGER NOT NULL,
  kind          TEXT    NOT NULL,
  text          TEXT    NOT NULL,
  -- ★ v4：public|org|granted（受规则 B1：min(块档位, 页面有效档位)，块只能更窄）
  visibility    TEXT    NOT NULL DEFAULT 'public',
  inherit       INTEGER NOT NULL DEFAULT 1,
  marker        TEXT,
  content_hash  TEXT    NOT NULL,
  created_at    TEXT    NOT NULL,
  updated_at    TEXT    NOT NULL,
  -- 密级冗余列：{ 0 = anon, 1 = org }；`granted` 档写 NULL。**无默认值**（失败关闭）——
  -- `DEFAULT 0` 会让漏算 tier 的块以匿名等级进索引，那是泄漏。
  tier          INTEGER
);

CREATE INDEX IF NOT EXISTS idx_blocks_page_ordinal ON blocks(page_id, ordinal);
CREATE INDEX IF NOT EXISTS idx_blocks_visibility ON blocks(visibility) WHERE visibility <> 'public';
CREATE INDEX IF NOT EXISTS idx_blocks_tier ON blocks(tier);
