-- 0016_block_grants.sql —— 块级例外授予（PostgreSQL 方言，P3b）
--
-- 与 packages/db-sqlite/src/migrations/0016_block_grants.sql **语义等价**。
-- 方言差异对照：
--
-- | 语义          | SQLite                            | PostgreSQL                                |
-- | ------------- | --------------------------------- | ----------------------------------------- |
-- | 自增主键      | INTEGER PRIMARY KEY AUTOINCREMENT | INTEGER GENERATED BY DEFAULT AS IDENTITY  |
-- | 时间列        | TEXT                              | TEXT（**刻意保持 TEXT**，两侧返回形状一致） |
-- | 幂等建表/索引 | IF NOT EXISTS                     | 同左                                      |
--
-- 其余口径（D13 授权对象只有 user|group、授权只放宽不收紧、`page_slug` 冗余仅供治理
-- 查询而不参与判定、`block_id` 用 CASCADE 而 `page_grants` 不用外键的理由、
-- `expires_at` 判定时比较而不依赖清理任务）与 SQLite 侧逐字对应，此处不再重复解释。
--
-- **不要写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS block_grants (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id     INTEGER NOT NULL REFERENCES blocks(id) ON DELETE CASCADE,
  page_slug    TEXT    NOT NULL,
  -- ★ D13：只有 user|group，没有 org_role。
  subject_kind TEXT    NOT NULL,
  subject_id   TEXT    NOT NULL,
  role         TEXT    NOT NULL,   -- editor|viewer
  granted_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
  granted_at   TEXT    NOT NULL,
  expires_at   TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_block_grants_unique
  ON block_grants(block_id, subject_kind, subject_id);

CREATE INDEX IF NOT EXISTS idx_block_grants_page
  ON block_grants(page_slug);

-- 检索热路径：按主体反查被授予的块（与 idx_page_grants_subject 对齐）
CREATE INDEX IF NOT EXISTS idx_block_grants_subject
  ON block_grants(subject_kind, subject_id);
