-- 0018_attachments.sql —— 附件元数据（PostgreSQL 方言，本批 M2/M3）
--
-- 与 packages/db-sqlite/src/migrations/0018_attachments.sql **语义等价**。
-- 该文件头部有完整的理由说明（为什么落在 db 包而不是 `@geewiki/wiki` 的迁移目录、
-- 为什么外键指向 pages(id) 而不是 slug、为什么唯一键是 (page_id, sha256)、
-- 磁盘与数据库的分工）—— 那些理由与方言无关，此处不重复。
--
-- 方言差异对照（与 0001_init.sql 的对照表同源）：
--
-- | 语义       | SQLite                             | PostgreSQL                                |
-- | ---------- | ---------------------------------- | ----------------------------------------- |
-- | 自增主键   | INTEGER PRIMARY KEY AUTOINCREMENT  | INTEGER GENERATED BY DEFAULT AS IDENTITY  |
-- | 文本       | TEXT                               | TEXT（PG 的 TEXT 无长度限制，语义一致）    |
-- | 时间       | TEXT（ISO8601 字符串）             | TEXT（**刻意保持 TEXT**：应用层写的是      |
-- |            |                                    |   new Date().toISOString()，改成           |
-- |            |                                    |   timestamptz 会让两个适配器的返回值形状   |
-- |            |                                    |   不一致，破坏"切换数据库对上层透明"）     |
-- | 外键级联   | REFERENCES … ON DELETE CASCADE     | 同左（语法一致）                          |
-- | 复合唯一键 | UNIQUE (page_id, sha256)           | 同左（内联写法一致）                      |
-- | 幂等建表   | CREATE TABLE IF NOT EXISTS         | 同左                                      |
--
-- 关于自增主键的写法：本仓 PG 迁移**一律用 `GENERATED BY DEFAULT AS IDENTITY`**
-- （0001/0010/0011/0012/0013/0014/0015/0016 全是这一形态），不是 `BIGSERIAL` ——
-- 两侧成对的文件必须保持同一种 id 语义，否则"切换数据库对上层透明"这条承诺在
-- 类型层面就破了（`id` 在 SQLite 是 64 位 INTEGER，PG 侧用 bigserial 会让返回形状漂移）。
--
-- **不写 BEGIN/COMMIT**：迁移控制器已把每个文件包在独立事务里。

CREATE TABLE IF NOT EXISTS attachments (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 外键到 id（不是 slug）：删页时元数据随 CASCADE 一起走，不留孤儿行
  page_id       INTEGER NOT NULL REFERENCES pages(id) ON DELETE CASCADE,
  -- 冗余的人类可读列（审计/排障）。**不参与任何判定** —— 判定用 pages.slug 现值联查。
  page_slug     TEXT    NOT NULL,
  -- 内容哈希：落盘路径的一半，也是幂等去重的唯一键
  sha256        TEXT    NOT NULL,
  -- 已过白名单的扩展名（含前导点、小写）：落盘路径的另一半，并决定响应头
  ext           TEXT    NOT NULL,
  byte_size     INTEGER NOT NULL,
  -- 由扩展名推出的 MIME（**不信任上传时的 Content-Type 声明**，见 attachments.ts）
  mime          TEXT    NOT NULL,
  -- 原始文件名：**只用于展示**（Content-Disposition），从不参与路径拼接
  original_name TEXT    NOT NULL,
  -- 上传者；老数据/系统导入可能为 NULL ⇒ 可空
  uploader_id   INTEGER,
  created_at    TEXT    NOT NULL,
  -- 同页同内容只一行（并发下的最后一道）
  UNIQUE (page_id, sha256)
);

-- 页面附件清单（`GET /api/pages/:slug/attachments` 与配额求和都走它）
CREATE INDEX IF NOT EXISTS idx_attachments_page ON attachments(page_id);
-- 跨页查同一份内容（GC 判据："还有没有元数据指向这个文件"）
CREATE INDEX IF NOT EXISTS idx_attachments_sha  ON attachments(sha256);
